#!/bin/bash
# Builds a Java program.
if [[ "$1" == "" ]]; then
	echo "Invalid Input (no filename)"
fi

FILE=$1
DIR=$( dirname $FILE )
cd $DIR

# Java, or Habanero Java?
if [[ "$( basename $FILE .java )" == "$FILE" ]]; then
	COMPILER="hjc"
	RUNTIME="hj"
else
	COMPILER="javac"
	RUNTIME="java"
fi

# Default / only classpath option: Include the current directory, and jar files
# that are in the current directory
CLASSPATH="."
for i in $( ls | grep [\.]jar ); do
	CLASSPATH="$CLASSPATH:./$i"
done

# Default / only file option: Include the files in the current directory
FILES=""
for i in $( ls | grep [\.]$RUNTIME ); do
	if [[ "$COMPILER" == "hjc" ]]; then
		$COMPILER -cp "$CLASSPATH" $i
	else
		FILES="$FILES $i"
	fi
done

### DEBUG
# echo "Java files: " $FILES
# echo "JAR files:  " $CLASSPATH
### DEBUG

# Compile java source files (hj files have been compiled one-by-one above)
if [[ "$COMPILER" == "javac" ]]; then
	$COMPILER -cp "$CLASSPATH" $FILES
fi
$RUNTIME -cp "$CLASSPATH" $( basename $FILE .$RUNTIME )
